name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - version-bumps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: npm run build
      - run: tar -cf webui.tar dist
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: webui.tar
          path: webui.tar

  publish-pr-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: 
      - build
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: webui.tar
      - name: Untar files
        run: tar -xf webui.tar dist

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist


  publish-web-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: 
      - build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: webui.tar
      - name: Untar files
        run: tar -xf webui.tar dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          clean: true
          clean-exclude: pr-preview/
          folder: ./dist