name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - version-bumps

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: cp dist/index.html dist/404.html
      - run: tar -cf webui.tar dist
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # tag=v3.0.0
        with:
          name: webui.tar
          path: webui.tar

  publish-pr-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs: 
      - build
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: webui.tar
      - name: Untar files
        run: tar -xf webui.tar dist

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.1.1
        with:
          source-dir: ./dist


  publish-web-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: 
      - build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3.0.0
        with:
          name: webui.tar
      - name: Untar files
        run: tar -xf webui.tar dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@360c8e75d0ee81732d0a5675c71e51b569df2ee8 # tag=v4.3.0
        with:
          clean: true
          clean-exclude: pr-preview/
          folder: ./dist
          branch: gh-pages